language: c
sudo: required
dist: xenial

install:
        - sudo apt-get update
        - sudo apt-get install -yy gcc-arm-none-eabi python-pip openssl
        - pip install asn1crypto --user

script:
        - 'cd src && make TARGET=TOMU && cd ..'
