language: c
dist: trusty

addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - python-pip
      - openssl

install:
  - pip install asn1crypto --user

script:
  - 'cd src && make TARGET=TOMU && cd ..'
  - 'cd src && make clean distclean certclean && cd ..'
  - 'cd src && make TARGET=MAPLE_MINI && cd ..'
  - 'cd src && make clean distclean certclean && cd ..'
  - 'cd src && make TARGET=BLUE_PILL && cd ..'
  - 'cd src && make clean distclean certclean && cd ..'
  - 'cd src && make TARGET=ST_DONGLE && cd ..'
